databases:
  - name: Smart Wallet
    databaseName: smart_wallet
    user: smart_wallet_user

services:
  - type: web
    name: Smart Wallet
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: smart_wallet
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false